### ISSUE TITLE
phpunit configuration file did not pass validation

### ISSUE THREAD

**Issue by marioquartz** [melbahja/seo#8]
> PHPUnit 8.5.21 by Sebastian Bergmann and contributors.
> 
>   Warning - The configuration file did not pass validation!
>   The following problems have been detected:
> 
>   Line 15:
>   - Element 'coverage': This element is not expected.

I cloned the repository and when do the tests with command "vendor/bin/phpunit" this error appears. But not stops the tests. And they are passed.

**Comment by melbahja** [comment]
phpunit 8.5 it only version i've found that can runs on php 7 and php 8. if we upgrade to phpunit v9 we should drop php 7 support
